name: Trigger RegressAI Test Generation

on:
  workflow_dispatch:
  push:
    paths:
      - 'app/src/main/java/com/mahyaddin/my_app/presentation/**/*.kt'
      - 'app/src/main/res/layout/**/*.xml'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed Activity and XML files
        id: get-files
        run: |
          git fetch origin master
          CHANGED_KT=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.kt$' | head -n 1)
          CHANGED_XML=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.xml$' | head -n 1)
          echo "kt_file=$CHANGED_KT" >> $GITHUB_OUTPUT
          echo "xml_file=$CHANGED_XML" >> $GITHUB_OUTPUT

      - name: Trigger RegressAI workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REGRESSAI_TRIGGER_TOKEN }}
          repository: mahyaddinjabbar/RegressAI
          event-type: trigger-test-generation
          client-payload: >-
            {
              "kt_file": "${{ steps.get-files.outputs.kt_file }}",
              "xml_file": "${{ steps.get-files.outputs.xml_file }}"
            }

